replicaCount: 1

image:
  repository: vault
  tag: "1.9.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8200

config:
  VAULT_DEV_ROOT_TOKEN_ID: "root"
  VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
